name: Build HHOS
run-name: Какой-то долбаёб играется с Github Workflows
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Установка зависимостей
        run: sudo apt update && sudo apt install xorriso mtools python3 nasm build-essential bison flex libgmp3-dev libmpc-dev libmpfr-dev texinfo
      - name: Чекаем код
        uses: actions/checkout@v3
      - name: Чекаем файлы в директории
        run: ls ${{ github.workspace }}
      - name: Чекаем от какого юзверя мы работаем
        run: whoami
      # - name: Устанавливаем кросс-компилятор
      #   run: